### ISSUE TITLE
Establish CKAN test environment 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/ckan-data-curator-integration#1]
Target CKAN v2.7.x https://github.com/ckan/ckan/releases

See https://github.com/frictionlessdata/ckanext-datapackager#developing-ckanext-datapackager

**Comment by Stephen-Gates** [comment]
CKAN installed
<img width="1000" alt="screenshot 2018-06-08 17 52 47" src="https://user-images.githubusercontent.com/9379524/41145955-152686bc-6b45-11e8-8da5-027643615cf1.png">

**Comment by Stephen-Gates** [comment]
Stephen to determine version of CKAN client is using

**Comment by Stephen-Gates** [comment]
datapackage  extension and tools installed.

<img width="1041" alt="screenshot 2018-06-17 19 46 23" src="https://user-images.githubusercontent.com/9379524/41506762-53e936be-7267-11e8-9c8a-c6caf87fbe52.png">

@louisjasek can you please confirm the versions for CKAN,  database, redis and solr?

**Comment by mattRedBox** [comment]
thanks @Stephen-Gates

**Comment by louisjasek** [comment]
Hi @Stephen-Gates @mattRedBox have asked the question - waiting on a response back from our vendor.

**Comment by louisjasek** [comment]
Hi @Stephen-Gates @mattRedBox just sent email with environment details

**Comment by Stephen-Gates** [comment]
Component | Current Version | Planned Version (if expected to change in next 12 months)
-- | -- | --
CKAN | 2.4.9 | 2.7.3
Database | 10.4 | 10.4
Redis | 2.8.4 | 2.8.4
Solr | 3.6.2 | 6.5.x
Python | 2.7.6 | 2.7.6

**Comment by mattRedBox** [comment]
thanks @louisjasek @Stephen-Gates

**Comment by mattRedBox** [comment]
Component | Current Version in UAT | Planned Version to match
-- | -- | --
CKAN | 2.7.0 | 2.7.3
Database | 10.4 | 10.4
Redis | 4.0.9 | 2.8.4
Solr | 6.6.2 | 6.5.x
Python | 2.7.9 | 2.7.6

**Comment by mattRedBox** [comment]
for now - I'm not going to worry too much about solr/redis (I'll match these if time and can be done easily without impact) as these have more to do with searching and indexing data and little to do with ckan changes (I note too that their version of redis is way behind) - thankfully db version is correct.
While not too far from what they're after I will ensure that ckan and python versions match

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates  and @louisjasek 
I've just been reviewing 0.1.0 and noted that these issues are meant to be kept 'live' and move across milestones (so have updated), when I noticed @Stephen-Gates this [adoption document](https://github.com/ODIQueensland/ckan-data-curator-integration/blob/master/docs/adoption.md):
In it you've recorded:

```
CKAN
To support uploading and downloading data packages:

CKAN v2.7.4 or higher must be installed (download)
```
I note that we are using 2.7.0 and downloads seem to be working fine both in dev and uat. Do you recall where this information came from?
The reason I'm asking is that I note Louis' capture of the planned versions has 2.7.3
Just want to be sure I haven't missed something in the document so far (I can correct from here @Stephen-Gates, but just wanted to be sure of the history first).

**Comment by Stephen-Gates** [comment]
2.7.4 came from Louie saying they were moving to 2.7.x. I stated 2.7.4 because it was the latest release

**Comment by mattRedBox** [comment]
thanks - will update.
