### ISSUE TITLE
Import a Data Package JSON to CKAN

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/ckan-data-curator-integration#30]
See [acceptance test ](https://app.cucumber.pro/projects/ckan-data-curator-integration/documents/branch/master/test/features/ckan/import-datapackage-json.feature)

Ensure that the [existing functionality](https://github.com/frictionlessdata/ckanext-datapackager/blob/master/README.markdown#using) imports all the metadata for a Data Package into CKAN. 

Valid test data:
- https://github.com/frictionlessdata/example-data-packages/blob/master/world-continents-topojson/datapackage.json

Invalid test data:
- https://raw.githubusercontent.com/ODIQueensland/ckan-data-curator-integration/master/test/data/invalid-data-packages/geo-lat-lon-as-numbers/datapackage.json
- https://github.com/frictionlessdata/example-data-packages/blob/master/geo-countries/datapackage.json data is not hosted elsewhere

**Comment by mattRedBox** [comment]
creating a dummy organization (which is then available for selection on download), 
and uploading valid datapackage.json
```
{
  "name": "world-continents-topojson",
  "title": "World Continents TopoJSON Example Data Package",
  "licenses": [{
    "title": "MIT License",
    "path": "http://www.opensource.org/licenses/MIT"
  }],
  "sources": [{
    "title": "TopoJSON Collection - World Continents",
    "path": "https://github.com/deldersveld/topojson/blob/master/world-continents.json"
  }],
  "resources": [{
    "path": "https://github.com/deldersveld/topojson/raw/master/world-continents.json",
    "name": "world-continents",
    "description": "World Continents",
    "format": "topojson",
    "mediatype": "application/json"
  }]
}
```

This record then, on download from ckan, becomes:

```
{
  "extras": {
    "licenses": [
      {
        "path": "http://www.opensource.org/licenses/MIT", 
        "title": "MIT License"
      }
    ], 
    "profile": "data-package"
  }, 
  "name": "world-continents-topojson", 
  "resources": [
    {
      "path": "https://github.com/deldersveld/topojson/raw/master/world-continents.json", 
      "title": "world-continents", 
      "description": "World Continents", 
      "name": "world-continents", 
      "format": "topojson"
    }
  ], 
  "title": "World Continents TopoJSON Example Data Package"
}
```

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Looking at [mapping](https://app.cucumber.pro/projects/ckan-data-curator-integration/documents/branch/master/test/features/metadata-mapping.md#data-package-to-ckan-dataset-mapping), I realise that it's in kindofa draft state, but how much of that is expected to be done in this sprint?

**Comment by mattRedBox** [comment]
And:
```
{
  "name": "geo-countries",
  "title": "Country Polygons as GeoJSON (Example)",
  "description": "Example Data Package providing GeoJSON polygons for all the world's countries",
  "licenses": [{
    "id": "CC0-1.0",
    "title": "CC0 1.0",
    "url": "https://creativecommons.org/publicdomain/zero/1.0/"
  }],
  "resources": [
    {
      "name": "countries",
      "path": "data/countries.geojson",
      "format": "geojson",
      "mediatype": "application/json",
      "schema": {
        "fields": [
          {
            "name": "ADMIN",
            "description": "Common name of the country",
            "type": "string"
          },
          {
            "name": "ISO_A3",
            "description": "3 characters code for the country, according to ISO3166 standard",
            "type": "string"
          }
        ]
      }
    }
  ]
}
```

becomes:
```
{
  "description": "Example Data Package providing GeoJSON polygons for all the world's countries", 
  "extras": {
    "licenses": [
      {
        "url": "https://creativecommons.org/publicdomain/zero/1.0/", 
        "id": "CC0-1.0", 
        "title": "CC0 1.0"
      }
    ], 
    "profile": "data-package"
  }, 
  "name": "geo-countries", 
  "resources": [
    {
      "path": "https://raw.githubusercontent.com/frictionlessdata/example-data-packages/master/geo-countries/data/countries.geojson", 
      "schema": "{u'fields': [{u'type': u'string', u'name': u'ADMIN', u'description': u'Common name of the country'}, {u'type': u'string', u'name': u'ISO_A3', u'description': u'3 characters code for the country, according to ISO3166 standard'}]}", 
      "title": "countries", 
      "name": "countries", 
      "format": "GeoJSON"
    }
  ], 
  "title": "Country Polygons as GeoJSON (Example)"
}
````

**Comment by mattRedBox** [comment]
@Stephen-Gates 
Any chance we have more comprehensive examples than these? Trying to make sense of mapping is difficult with only these tests to go by?
Perhaps we're not be there yet?, but would be good to show in github issue, what a comprehensive example becomes atm, then show the expectation of what this should be in the acceptance test.

**Comment by Stephen-Gates** [comment]
I think scope should be a least fix mappings in https://github.com/ODIQueensland/ckan-data-curator-integration/issues/2

I’ll look deeper

**Comment by Stephen-Gates** [comment]
Creating an organisation is done manually in the user interface and not created by this feature. The organisation is needed to add data and assumed to pre-exist

**Comment by Stephen-Gates** [comment]
See https://github.com/frictionlessdata/ckanext-datapackager/issues/62#issuecomment-364224790 for `licenses`.

So in your [first example](https://github.com/ODIQueensland/ckan-data-curator-integration/issues/30#issuecomment-396135689) there wouldn't be `extras` in the download, just the standard [`licences`](https://frictionlessdata.io/specs/data-package/#licenses) from the spec.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Just put them there for reference for work on this ticket - what would be good would be to have examples that have more than just licenses.

**Comment by Stephen-Gates** [comment]
Just created test datapackage with more properties https://raw.githubusercontent.com/ODIQueensland/ckan-data-curator-integration/da2f80af24509aece042884412ca22fac13ecf55/test/data/valid-data-packages/cpi-data-via-url/datapackage.json

Uploading to CKAN using data-packager extension 

<img width="972" alt="screenshot 2018-06-23 11 31 22" src="https://user-images.githubusercontent.com/9379524/41804406-61b812da-76d9-11e8-94b1-d052950f4921.png">

<img width="750" alt="screenshot 2018-06-23 11 32 16" src="https://user-images.githubusercontent.com/9379524/41804409-7155b972-76d9-11e8-80c1-78a97bdac348.png">

<img width="758" alt="screenshot 2018-06-23 11 33 39" src="https://user-images.githubusercontent.com/9379524/41804413-8184714e-76d9-11e8-92f9-2901547253a0.png">
