### ISSUE TITLE
Download Data Package JSON file from CKAN

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/ckan-data-curator-integration#4]
See [Acceptance test](https://app.cucumber.pro/projects/ckan-data-curator-integration/documents/branch/master/test/features/ckan/download-datapackage-json.feature)

**Comment by Stephen-Gates** [comment]
Stephen to provide example of current download data package from old.datahub.org

**Comment by mattRedBox** [comment]
Check what Data Curator does with zips that have urls as resources.
May be able to avoid having ckan handle this, given concerns about keeping lightweight.
